version: '3'
services:
  packing_service:
    build:
      context: ./packing_service/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mynetwork

  ds_server:
    build:
      context: ./ds_server/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - mynetwork

networks:
  mynetwork:
